### ISSUE TITLE
your Homepage link in github is broken and issue n fix missing javafx description   

### ISSUE THREAD

**Issue by velletti** [edencoding/javafx-ui#1]
Hi Eden

as i found no othe possability to contact you, try it this way : 
in your github profile the link unter your profle leads to codingeden.com but should be for shure edencoding.com  

And on: 
https://edencoding.com/runtime-components-error/ 

On Windows this does not work as it actually needs  "="  after --module-path. and --add-modules

--module-path=/path/to/javafx-sdk-14/lib --add-modules=javafx.controls,javafx.fxml

**Comment by edencoding** [comment]
Thanks Valetti!

Really appreciate you reaching out. There's a contact form on the right sidebar of the webpage, but appreciate it might not be totally obvious. 

Have fixed the web link to edencoding, and will look into the runtime components issue - thanks!

As neither are relevant to this repo, I'll close this issue with gratitude for the errors you've spotted

Thanks,

Ed
